service: serverless-hello

plugins:
  - serverless-offline
  
provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true