service: serverless-hello

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true

  status:
    handler: handler.status
    events:
      - http:
          path: status
          method: get
          cors: true
  submit:
    handler: handler.submit
    events:
      - http:
          path: submit
          method: post
          cors: true
