service: serverless-hello

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Scan
          Resource: arn:aws:dynamodb:eu-west-1:070853583236:table/SubmissionTable
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        - Fn::GetAtt: [SubmissionTable, Arn]

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true

  status:
    handler: handler.status
    events:
      - http:
          path: status
          method: get
          cors: true
    
  submit:
    handler: handler.submit
    events:
      - http:
          path: submit
          method: post
          cors: true

  list:
    handler: handler.list
    events:
      - http:
          path: list
          method: get
          cors: true


resources:
  Resources:
    SubmissionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SubmissionTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

package:
  exclude:
    - test/**
    - .git/**
    - .env
    - README.md
    - node_modules/aws-sdk/**